#!/usr/bin/env ruby

require_relative 'lib/environment'
Environment.environment = ENV["DB"] || "development"

require_relative 'lib/router'

ARGV
case ARGV.length
  when 1
  when 2
  when 3
    SongsController.key(ARGV[0], ARGV[1], ARGV[2])
  else
    puts "welcome to dj list"
    Router.welcome()
end
